##################################################

api_network_base_url: http://redjungle-00.lab

##################################################

orchestration_service_port: 7001
review_service_port: 7005
auth_service_port: 7010
access_control_service_port: 7020
tenant_service_port: 7030
hotel_service_port: 7040
room_service_port: 7050
payment_gateway_service_port: 7060
booking_service_port: 7070
user_service_port: 7080
analytics_service_port: 7090
audit_logging_service_port: 7095

##################################################








